### PR TITLE
Compatibility with Transparent Panels

### PR DESCRIPTION
**Pull request by dominichayesferen**
Ok, this will mean that you HAVE to use Transparent Panels for the Vista Aero theme, but didn't Vista have opaque taskbars anyway when a window is maximized?

### CODE REVIEW

**Comment by dominichayesferen** [comment]
Fixes https://github.com/B00merang-Project/Redmond-Themes/issues/24

**Comment by ghost** [comment]
@feren Yes, they are opaque when maximized. I mean the real Vista. If you achieved integration I wanna see it.

**Comment by dominichayesferen** [comment]
@cinnamoner The only catch with this integration is that you NEED the extension called 'Transparent Panels' installed and enabled, and have it set on 'Defined by theme'

**Comment by dominichayesferen** [comment]
Now in another Request...

**Pull request closed without merging**
