### PR TITLE
Start Button that actually works through the panel itself

### PR DESCRIPTION
**Pull request by dominichayesferen**
Accept it, and you'll be able to have a start button that comes out of the panel like in Vista thanks to ORBWin...
- It works on maximised windows

screenshot from 2016-10-13 17-03-01

### CODE REVIEW

**Comment by ghost** [comment]
@feren @Elbullazul How can I get it?

**Comment by ghost** [comment]
Whenever a merging happens, does it get into masterzip?

**Comment by dominichayesferen** [comment]
It goes to master when merged

**Comment by dominichayesferen** [comment]
Now to delete the source of the Pull Request since it's merged. :)

**Pull request merged**
